### ISSUE TITLE
Building `serde-sarif` requires `rustfmt` to be installed

### ISSUE THREAD

**Issue by jonasbb** [psastras/sarif-rs#212]
Building `serde-sarif` requires that `rustfmt` is installed at build time. This seems unnecessary. The build script could just compile the unformatted code, if either `rustfmt` is unavailable or it fails for some other reasons.

More generally, the code generation is not necessary during build time and could be done earlier. I say that, because it looks like it only depends on the `schema.json` file, but this file is not platform-dependent, so there is no need for build time code generation. One pattern which can be used here is code generation with tests. There is a whole blog post about this topic by `@matklad` <https://matklad.github.io/2022/03/26/self-modifying-code.html#self-modifying-code>. This would have the added benefit of not compiling any build dependencies.

**Comment by psastras** [comment]
this makes a lot of sense to me. I would like to keep the formatted code, because it's nice to read in things like [docs.rs](https://docs.rs/serde-sarif/0.3.0/src/serde_sarif/opt/rustwide/target/x86_64-unknown-linux-gnu/debug/build/serde-sarif-fbaad3752efa34dc/out/sarif.rs.html#2298-2317) or IDE go to definition.

the test approach lgtme!
